### ISSUE TITLE
Not able to run the repo

### ISSUE THREAD

**Issue by fyang93** [goatchurchprime/lipsync#3]
I encountered a bunch of errors when running this repo in godot 4.3.
I tried to fix a few errors but still cannot get this repo working.
Some known errors in `main.gd`:
```
var chunkv1 = audioopuschunkedeffect.chunk_max() // expect 2 args, I tried (false, false)
var chunkv2 = audioopuschunkedeffect.chunk_rms() // Nonexist function chunk_rms in base AudioEffectOpusChunked
$ChunkMax.value = chunkv2*100
if $AudioStreamMicrophone.playing and audioopuschunkedeffect.chunk_to_lipsync() != -1: // chunck_to_lipsync expects 1 arg, I tried (false)
```

I just stuck there and cannot run properly.
I would appreciate any suggestions :)

**Comment by goatchurchprime** [comment]
I changed a couple of the functions in the plugin.  Fixed now.

What platform are you using this on?  And what's your application?

If you are in a noisy environment, you can call `denoise_resampled_chunk()` to filter out the noise.

If you are trying to lipsync a face, it might be worth treating these viseme values as probabilities and animating to a single one for an interval, then quickly animating to the next most likely, rather than treating it as a blend of all of them.  

Also, there is a lag in the viseme detection, so it will look great if you can lag the audio by the right amount to match it.  I don't know what amount this will be.
